import qrcode
features=qrcode.QRCode(version=1,box_size=40,border=3)
features.add_data('https://www.linkedin.com/in/nikitha-vytla-42135520b')
features.make(fit=True)
qr=features.make_image(fill_color='blue',back_color="white")
qr.save("docpy.png")
features1=qrcode.QRCode(version=2,box_size=30,border=2)
features1.add_data('https://github.com/Nikithavytla03?tab=projects')
features1.make(fit=True)
qr1=features1.make_image(fill_color="green",back_color="white")
qr1.save("docpy1.png")
features2=qrcode.QRCode(version=1,box_size=40,border=3)
features2.add_data("you can contact me by" "" +'nikithavytla03@gmail')
features2.make(fit=True)
qr2=features2.make_image(fill_color="black",back_color="white")
qr2.save("docpy2.png")
features3=qrcode.QRCode(version=1,box_size=40,border=3)
features3.add_data('contact me by 8374260239')
features3.make(fit=True)
qr3=features3.make_image(fill_color="black",back_color="white")
qr3.save("docpy3.png")
features4=qrcode.QRCode(version=1,box_size=40,border=3)
features4.add_data('https://www.hackerrank.com/certificates/559bb7da3bbd')
features4.make(fit=True)
qr4=features4.make_image(fill_color="blue",back_color="white")
qr4.save("docpy4.png")
features5=qrcode.QRCode(version=1,box_size=40,border=3)
features5.add_data('https://olympus.mygreatlearning.com/courses/50633/certificate')
features5.make(fit=True)
qr5=features5.make_image(fill_color="blue",back_color="white")
qr5.save("docpy5.png")
